provider"aws"{
region="us-west-2"
}
resource"aws_instance""example"{
ami="ami-00cdefsg"
instance_type="t2.micro"
tags={
name="example_instance"
}
vpc_security_group_ids=[aws_security_group.instance_sg.id]
}
}
resource"aws_security_group""instance_sg"{
name="instance_sg"
description="Allow SSH inbound traffic"
ingress{
from_port=22
to_port=22
protocol="tcp"
cidr_blocks=["0.0.0.0/0"]
}
egress{
from_port=0
to_port=0
protocol="-1"
cidr_blocks=["0.0.0.0/0"]
}
}
